### ISSUE TITLE
Remove jq as a dependency?

### ISSUE THREAD

**Issue by cmckni3** [jzelinskie/faq#13]

**Comment by jzelinskie** [comment]
I'm responded to this even though you closed it like a year ago.

I don't think I want to totally remove jq as a dependency unless there's a community that agrees on doing so. If we removed the dependency, there would forever be a game of reimplementing new builtins, etc... in jq for compatibility. I'd rather just import it unless the majority of users decided that compatibility with jq isn't what they care about.

**Comment by cmckni3** [comment]
Apologies, I thought faq shells out to the jq binary. Looked through the code and realized it doesn’t (iirc). So I went ahead and closed the issue.

Great tool btw :thumb_up:
