### ISSUE TITLE
Document use of Dockerfile to build

### ISSUE THREAD

**Issue by vielmetti** [jzelinskie/faq#14]
I think it's as simple as 

```
git clone https://github.com/jzelinskie/faq
cd faq
docker build .
```

to build using the supplied Dockerfile; but I couldn't find where the generated binary by the build was supposed to go.

**Comment by jzelinskie** [comment]
```
docker build -t quay.io/jzelinskie/faq:latest . && docker create quay.io/jzelinskie/faq:latest && docker cp `docker ps -aq | head -1`:/go/bin/faq faq-linux-amd64
```

**Comment by jzelinskie** [comment]
There's been a Makefile for a while now and one can look at CI or the Dockerfile to see how to install dependencies for building on Linux, so I'm going to close this now.
