### ISSUE TITLE
Drone Cloud

### ISSUE THREAD

**Issue by vielmetti** [jzelinskie/faq#38]
As mentioned in #11 Drone Cloud has a 32-bit Arm build/test environment as well as arm64 and x86. This issue to track adding a Drone configuration (.drone.yml) and explore this build environment for faq.

**Comment by jzelinskie** [comment]
I'm not familiar with Drone already, but if it can build test arm64 linux, x86 linux, x86 darwin on PRs and have it build release artifacts for tags, that checks all the boxes for me.

**Comment by jzelinskie** [comment]
I'm closing in favor of #83, because I want to only use GitHub actions if possible.
