### ISSUE TITLE
Feature request: `YAML stream` format

### ISSUE THREAD

**Issue by mumoshu** [jzelinskie/faq#5]
Hi, thanks for maintaining a great project!

Would you mind if I contributed this feature?

Context:

I wanted to use faq for manipulating a YAML stream, as well as I use jq for manipulating NDJSON(Or line-delimited JSON).

A YAML stream would look like this. It is basically multiple YAML docs separated by `---`:

```
$ jsonnet -y /dev/stdin <<< '[{x: 1, y: self.x} + {x: 10}, {z: 2}]'
---
{
   "x": 10,
   "y": 10
}
---
{
   "z": 2
}
...
```

Current it doesn't work, obviously, as faq supports a YAML array in a single YAML file only, rather than a YAML stream:

```
$ jsonnet -y /dev/stdin <<< '[{x: 1, y: self.x} + {x: 10}, {z: 2}]' | faq
Error: no supported format found named auto
Usage:
  faq [flags] [filter string] [files...]

Flags:
  -a, --ascii-output        force output to be ascii instead of UTF-8
  -C, --color-output        colorize the output (default true)
  -c, --compact             compact instead of pretty-printed output
  -f, --format string       input format (default "auto")
  -h, --help                help for faq
  -m, --maintain-format     maintain original format (don't output JSON)
  -M, --monochrome-output   monochrome (don't colorize the output)
  -r, --raw                 output raw strings, not JSON texts
  -S, --sort-keys           sort keys of objects on output
  -t, --tab                 use tabs for indentation
```

Note that the error message `Error: no supported format found named auto` is rather confusing as it doesn't correctly express the fact that faq was just unable to auto-detect the format.
I'll open an another dedicated issue for that!

**Comment by jzelinskie** [comment]
>Hi, thanks for maintaining a great project!

Thanks!

>Would you mind if I contributed this feature?

Please do! I'm totally open to pull requests and opinions on the project and its direction.
Because I'm also using this project for Kubernetes resources, I too would like YAML stream support. You'll notice that this project uses the same library as Kubernetes for YAML encoding/decoding.

**Comment by chancez** [comment]
We're waiting on either https://github.com/ghodss/yaml/pull/47 or https://github.com/kubernetes-sigs/yaml/pull/12 and then this will just work once we update/switch the package.

**Comment by chancez** [comment]
Update: instead of trying to get changes into the mentioned yaml packages (which didn't actually fully work anyway) I've opted to do another approach directly in faq. See #25.
