### ISSUE TITLE
Support reading jq program/filter from file

### ISSUE THREAD

**Issue by chancez** [jzelinskie/faq#68]
`jq` has the following flag as an option:
```
       o   -f filename / --from-file filename:

           Read filter from the file rather than from a command line, like awk's -f option. You can also use '#' to make comments.
```

`faq` should have something similar.

**Comment by jzelinskie** [comment]
This conflicts with the existing `-f` flag which is for the input format, but I can understand the desire to add this functionality. A workaround could be using the party hat operator:
```sh
$ faq '.' <(myFile.json)
```

**Comment by chancez** [comment]
I'm an idiot, this does exist. 
>   -F, --program-file string          If specified, read the file provided as the jq program for faq.

I even added it. I just had an old cached build around.

**Comment by jzelinskie** [comment]
I wonder if we should swap the flags for compat, though.
