### ISSUE TITLE
README is hostile

### ISSUE THREAD

**Issue by mythmon** [jzelinskie/faq#69]
While reviewing this project to figure out if it does what I'm looking for, I came across this line in the README:

> How do you pronounce "faq"? Fuck you.

It strikes me as very hostile. The README is the first contact many users have with a project, and this one is telling me "fuck you" within the first few paragraphs. As it stands, I wouldn't recommend this project to anyone, because I'd have to explain that line in the README. I'm sure that there are plenty of people that turned away immediately and didn't say anything.

**Comment by jzelinskie** [comment]
Hey there!

The name of the project is a joke: it's pronounced _fʌkju_ (if I got the [IPA] correct). I'm open to suggestions on how to expose this joke in such a way that it doesn't appear to be directed towards the reader.

Fundamentally, there will always be a portion of people that won't appreciate this kind of humor. It's totally fine to refuse to use or recommend something based on philosophy; developers do it all the time with regards to licensing.

Speaking of licensing, the project is licensed Apache 2.0. Legally, anyone that wants to maintain a fork that renames the project is free to do so.

If I have personally offended you, I am sorry.

[IPA]: https://en.wikipedia.org/wiki/International_Phonetic_Alphabet
