### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by irushabhshah** [jzelinskie/faq#94]
Hello @jzelinskie 

I've been trying to install faq on aws ec2 linux and when executing _make all_ it shows me a couple of errors as following:
_/usr/bin/ld: cannot find -ljq_
_/usr/bin/ld: cannot find -lonig_

```
[ec2-user@ip-10-0-134-98 faq]$ ls
cmd  Dockerfile  docs  go.mod  go.sum  internal  LICENSE  Makefile  pkg  README.md
[ec2-user@ip-10-0-134-98 faq]$ make all
golint ./...
go test ./...
# github.com/jzelinskie/faq/internal/jq
/usr/bin/ld: cannot find -ljq
/usr/bin/ld: cannot find -lonig
collect2: error: ld returned 1 exit status
FAIL    github.com/jzelinskie/faq/internal/faq [build failed]
ok      github.com/jzelinskie/faq/pkg/objconv   (cached)
make: *** [test] Error 2
[ec2-user@ip-10-0-134-98 faq]$
```

**Comment by jzelinskie** [comment]
Your linker is looking for the dynamic libraries to be installed on the system libjq and libonig (oniguruma).

**Comment by irushabhshah** [comment]
I forget to update. I was able to resolve this. Thank you.

**Comment by irushabhshah** [comment]
I forget to update. I was able to resolve this. Thank you.
